echo '===============================\n'
echo 'Installing Dracula theme...\n'
echo '===============================\n'
echo 'running....'
echo 'running....'
echo 'running....'
echo 'running....'
echo 'running....'
echo 'running....'
echo 'running....'
